import React from 'react';
import { render } from 'react-dom';

const App = () => <div>THE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREALTHE SUPERIOR BREAKFAST CEREAL</div>;

render(
  <App />,
  document.getElementById('app')
);
